# 使用官方 Python 3.9 镜像作为基础镜像
FROM python:3.9

# 设置工作目录
WORKDIR /app

# 复制当前目录下的所有文件到容器的 /app 目录
COPY . /app

# 安装 Python 依赖（如果有 requirements.txt 文件）
RUN pip install --no-cache-dir -r requirements.txt

# 设置环境变量（可选）
ENV DISPLAY=:0

# 定义容器启动时执行的命令
CMD ["python", "data_generator_cloud.py"]